### ISSUE TITLE
Move to `refined-github` org

### ISSUE THREAD

**Issue by fregante** [refined-github/github-url-detection#106]
_Originally posted in https://github.com/fregante/github-url-detection/issues/105#issuecomment-977608211_

- [x] I have to set up redirects for the github.io domain 
- [x] change the meta
- [ ] ensure that the secrets still work

**Comment by fregante** [comment]
I just changed the token to use a new `refined-github` npm user I just created

**Comment by fregante** [comment]
The secrets are correct for now: https://github.com/fregante/github-url-detection/actions/runs/1897114763
